CREATE TABLE TBTCLIENTE (
    CPF VARCHAR2(15) PRIMARY KEY,
    NOME VARCHAR2(20) NOT NULL,
    ENDERECO VARCHAR2(50),
    CIDADE VARCHAR2(20),
    TELEFONE VARCHAR2(15) NOT NULL,
    RG VARCHAR2(20),
    DATA_INSCRICAO DATE,
    PONTOS_FIDELIDADE NUMBER(5)
);

CREATE TABLE TBTCATEGORIA (
    COD_CATEGORIA NUMBER(5) PRIMARY KEY,
    CATEGORIA VARCHAR2(20) NOT NULL
);

CREATE TABLE TBTCARRO (
    PLACA_CARRO VARCHAR2(15) PRIMARY KEY,
    MARCA VARCHAR2(15) NOT NULL,
    COD_CATEGORIA NUMBER(5) REFERENCES TBTCATEGORIA
);

CREATE TABLE TBTSEGURO (
    ID_SEGURO NUMBER(5) PRIMARY KEY,
    TIPO VARCHAR2(20) NOT NULL,
	VALOR NUMBER(6,2)
);

CREATE TABLE TBTLOCACAO (
    COD_LOCACAO NUMBER(5) PRIMARY KEY,
    DATA_LOCACAO DATE NOT NULL,
    DATA_DEVOLUCAO DATE NOT NULL,
    PRECO_DIARIA NUMBER(6,2) NOT NULL,
    VALOR_TOTAL NUMBER(8,2) NOT NULL,
    CARTAO_CLI NUMBER(10),
    CPF_CLI VARCHAR2(15) REFERENCES TBTCLIENTE,
    PLACA_CARRO VARCHAR2(15) REFERENCES TBTCARRO
);

CREATE TABLE TBTSEGURO_LOCACAO (
    ID_SEGURO NUMBER(5) REFERENCES TBTSEGURO,
    COD_LOCACAO NUMBER(5) REFERENCES TBTLOCACAO,
	PRIMARY KEY(ID_SEGURO,COD_LOCACAO)
);
