--5.1
CREATE TABLE TBTCLIENTESAPG(
	CPF VARCHAR2(15) PRIMARY KEY,
	NOME VARCHAR2(20) NOT NULL,
	TELEFONE VARCHAR2(15) NOT NULL,
	DT_EXCLUSAO DATE NOT NULL,
	USR_EXCLUSAO VARCHAR2(20) NOT NULL
);

CREATE OR REPLACE TRIGGER EXCLUI_CLIENTE
	
	BEFORE DELETE ON TBTCLIENTE
	FOR EACH ROW
	BEGIN
		INSERT INTO TBTCLIENTESAPG 
		VALUES (:OLD.CPF , :OLD.NOME , :OLD.TELEFONE , SYSDATE ,USER);
	END;
	
--5.3
CREATE OR REPLACE TRIGGER ADD_PONTOS
	
	AFTER UPDATE OF DATA_DEVOLUCAO ON TBTLOCACAO
	FOR EACH ROW
	DECLARE
		VPTS_FIDELIDADE TBTCLIENTE.PONTOS_FIDELIDADE%TYPE;
		VPLACA TBTCARRO.PLACA_CARRO%TYPE;
		VCOD_CATEGORIA TBTCARRO.COD_CATEGORIA%TYPE;
		VCPF TBTCLIENTE.CPF%TYPE;
	BEGIN
		SELECT PONTOS_FIDELIDADE INTO VPTS_FIDELIDADE
		FROM TBTCLIENTE
		WHERE CPF = :NEW.CPF_CLI;
		
		SELECT COD_CATEGORIA INTO VCOD_CATEGORIA
		FROM TBTCARRO
		WHERE PLACA_CARRO = :NEW.PLACA_CARRO;

		IF VCOD_CATEGORIA = 1 THEN
			VPTS_FIDELIDADE := VPTS_FIDELIDADE + 1;
		ELSIF VCOD_CATEGORIA = 2 THEN
			VPTS_FIDELIDADE := VPTS_FIDELIDADE + 2;
		ELSIF VCOD_CATEGORIA = 3 THEN
			VPTS_FIDELIDADE := VPTS_FIDELIDADE + 3;
		ELSIF VCOD_CATEGORIA = 4 THEN
			VPTS_FIDELIDADE := VPTS_FIDELIDADE + 4;
		END IF;
		
		UPDATE TBTCLIENTE 
		SET PONTOS_FIDELIDADE = VPTS_FIDELIDADE
		WHERE TBTCLIENTE.CPF = :NEW.CPF_CLI;
			
	END;

UPDATE TBTCLIENTE
SET PONTOS_FIDELIDADE = 0;

UPDATE TBTLOCACAO
SET DATA_DEVOLUCAO = '20/11/2016'
WHERE COD_LOCACAO = 2;