--5.2
CREATE OR REPLACE PROCEDURE VALOR_TOTAL_LOCACAO(P_cod_locacao NUMBER)
	AS 
    V_TOTAL NUMBER(10,2);
		V_SEGURO NUMBER(5);
		V_CPF VARCHAR2(15);
		V_NOME VARCHAR2(20);
		V_DATA DATE;

	BEGIN
		SELECT(DATA_DEVOLUCAO - DATA_LOCACAO) * PRECO_DIARIA, CPF_CLI, DATA_LOCACAO INTO V_TOTAL, V_CPF, V_DATA 
		FROM TBTLOCACAO
		WHERE COD_LOCACAO = P_cod_locacao;
		
		SELECT SUM(VALOR) INTO V_SEGURO
		FROM TBTSEGURO
		WHERE ID_SEGURO IN( SELECT ID_SEGURO
							FROM TBTSEGURO_LOCACAO
							WHERE COD_LOCACAO = P_cod_locacao);
							
		V_TOTAL := V_TOTAL + V_SEGURO;
		
		UPDATE TBTLOCACAO 
		SET VALOR_TOTAL = V_TOTAL
		WHERE COD_LOCACAO = P_cod_locacao;
		
		SELECT NOME INTO V_NOME
		FROM TBTCLIENTE
		WHERE CPF = V_CPF;
		
		INSERT INTO TBTPROCEDUREVTOTAL
		VALUES(P_cod_locacao, V_NOME, V_DATA, V_TOTAL);
		
	END;
	
	CREATE TBTPROCEDUREVTOTAL(
	CODIGO NUMBER(5) PRIMARY KEY,
	NOME VARCHAR2(20),
	VDATA DATE,
	TOTAL NUMBER(10,2);
	);

--5.5
CREATE OR REPLACE PROCEDURE VERIFICA_MANUTENCAO(COD_CARRO VARCHAR2)
AS
    V_LOCACOES NUMBER(5);
BEGIN
    SELECT COUNT(*) INTO V_LOCACOES
    FROM TBTLOCACAO
    WHERE TO_CHAR(DATA_DEVOLUCAO,'MM') = 10 AND PLACA_CARRO = COD_CARRO;

    IF V_LOCACOES > 10 THEN
        DBMS_OUTPUT.PUT_LINE('Veiculo devera passar por manutencao preventiva');
		
		INSERT INTO TBTPROCEDUREVERIFICAMANU
		VALUES(COD_CARRO,'OUTUBRO',SYSDATE);
        
    END IF;

END;

CREATE TBTPROCEDUREVERIFICAMANU(
	PLACA VARCHAR2(15) PRIMARY KEY,
	MES VARCHAR(15),
	DATA_ENVIO DATE
);	

