--5.6
CREATE OR REPLACE FUNCTION F_VERIFICAPTSFIDELIDADES(PCPF VARCHAR2)
	RETURN VARCHAR2
  
	AS VPONTOS NUMBER(5);
	BEGIN
		SELECT PONTOS_FIDELIDADE INTO VPONTOS
		FROM TBTCLIENTE
		WHERE CPF = PCPF;
		
		IF VPONTOS > 200 THEN
			RETURN 'Cliente tem direito a 10% de desconto no valor da diária';
 
		ELSIF VPONTOS BETWEEN 100 AND 200 THEN
			RETURN 'Cliente tem direito a 5% de desconto no valor da diária';
		ELSE
			RETURN'Cliente não tem direito a desconto no valor da diária';
    END IF;
END;

SELECT CPF, F_VERIFICAPTSFIDELIDADES(CPF)
FROM TBTCLIENTE;

--5.4
CREATE OR REPLACE FUNCTION CONTA_LOCACOES(CPF VARCHAR2)
RETURN VARCHAR2

AS
    N_LOCACOES NUMBER(5);
    CLI_EXISTE NUMBER(2);

BEGIN

    SELECT COUNT(*) INTO N_LOCACOES
    FROM TBTLOCACAO
    WHERE CPF_CLI = CPF;

    SELECT COUNT(*) INTO CLI_EXISTE
    FROM TBTCLIENTE
    WHERE TBTCLIENTE.CPF = CPF;

    IF CLI_EXISTE = 0 THEN
        RETURN 'Cliente inexistente';
    ELSE
        IF N_LOCACOES > 5 THEN
            RETURN 'Cliente preferencial';
        ELSIF N_LOCACOES >= 1 THEN
            RETURN 'Cliente normal';
        ELSE
            RETURN 'Cliente inativo';
        END IF;
    END IF;

END;


-- SELECT *
-- FROM DUAL;
